name: jetleaf_env
description: A library for accessing environment configuration and active profiles. It adds support for profile activation and resolutionâ€”typically used for conditional configuration based on the current runtime context.
version: 1.0.0

publish_to: none

homepage: https://jetleaf.hapnium.com
repository: https://github.com/jetleaf/jetleaf_env

topics:
- Environment Variables
- Interpolation
- Property Resource
- Property Loading
- Environment Profiles
- Environment Context
- Property Resolution

keywords:
- Environment Variables
- Interpolation
- Property Resource
- Property Loading
- Environment Profiles
- Environment Context
- Property Resolution

environment:
  sdk: ^3.9.0

dependencies:
  jetleaf_lang:
    path: ../jetleaf_lang
  jetleaf_logging:
    path: ../jetleaf_logging
  jetleaf_convert:
    path: ../jetleaf_convert
  jetleaf_utils:
    path: ../jetleaf_utils

dev_dependencies:
  test: ^1.21.0
  lints: ^6.0.0