name: jetleaf_env
description: Provides environment configuration, property access, and profile activation.
version: 1.0.0+2

homepage: https://jetleaf.hapnium.com
repository: https://github.com/jetleaf/jetleaf_env
issue_tracker: https://github.com/jetleaf/jetleaf_env/issues
documentation: https://jetleaf.hapnium.com/docs/env

topics:
  - environment
  - configuration
  - properties
  - profiles
  - jetleaf

keywords:
  - environment
  - configuration
  - properties
  - profiles
  - jetleaf

environment:
  sdk: ^3.9.0

dependencies:
  meta: ^1.17.0
  jetleaf_lang: 
    path: ../jetleaf_lang
  jetleaf_logging: 
    path: ../jetleaf_logging
  jetleaf_convert: 
    path: ../jetleaf_convert
  jetleaf_utils: 
    path: ../jetleaf_utils

dev_dependencies:
  test: ^1.21.0
  lints: ^6.0.0